#%RAML 1.0
title: testing
/raml:
  get:
    queryParameters:
      mule:
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            example:
              {
                "raml":"succesfully done"
              }